name: deal_baron
description: "Deal Baron - Online Multiplayer İş Simülasyon Oyunu"
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Models & Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Storage
  shared_preferences: ^2.3.3

  # UI
  gap: ^3.0.1

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1

  # Network & API
  dio: ^5.4.0
  http: ^1.1.0
  socket_io_client: ^2.0.3+1

  # Secure Storage
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.1
  freezed: ^2.5.7
  json_serializable: ^6.9.2

  # Icon Generation
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/data/
    - assets/images/

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

  # Android Adaptive Icon
  adaptive_icon_background: "#1a1a2e"
  adaptive_icon_foreground: "assets/images/app_icon.png"

  # iOS
  remove_alpha_ios: true
